In [ ]:
import numpy as np

Задание 1

In [ ]:
A = np.array(
[[1,2,1],
[-1,2,1]]
)
B = np.array(
    [[3,1],
    [-1,0],
    [2,4]]
)
C = np.array(
    [[-2,2],
     [1,-1],
      [1,2]]
)
print(f"A+2B = \n{A.T + 2*B}\n")
print(f"B+2C = \n{B + 2*C}\n")


A+2B = 
[[7 1]
 [0 2]
 [5 9]]

B+2C = 
[[-1  5]
 [ 1 -2]
 [ 4  8]]



Задание 2

In [ ]:
a = np.zeros([8,8])
a[::2,::2]=1
a[1::2,1::2]=1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Задание 3

In [ ]:
vec1= np.linspace(0, 1.4, num=15)
vec2= np.linspace(1, 6, num=6)
print(f"vec1: {vec1} \nvec2: {vec2}\n")

print(f"Result: \n{np.dot(np.reshape(vec1, [5,3]), np.reshape(vec2, [3,2]))}")

vec1: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4] 
vec2: [1. 2. 3. 4. 5. 6.]

Result: 
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


Задание 4

In [ ]:
vec = np.arange(1,36*2+1,2).astype(np.int32)
print(f"len of array: {len(vec)} \nType of array element: {type(vec[0])}")

len of array: 36 
Type of array element: <class 'numpy.int32'>


In [ ]:
print(f"Initial vec: {vec} \nVec %3 == 0: {vec[np.where(vec % 3 == 0)]}")

Initial vec: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71] 
Vec %3 == 0: [ 3  9 15 21 27 33 39 45 51 57 63 69]
